### ISSUE TITLE
Can't build on M1 chip

### ISSUE THREAD

**Issue by Vincen-Jo** [usnistgov/REFPROP-cmake#52]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/80340673/110496507-e11f2b00-8138-11eb-93f0-9574ad65de9f.png">

Hi,

I am a beginner in programming.
My question may be absurd, but I need your help.
I proceed one by one by following the procedure here.
However, when I run cmake, an error like the picture above appears.
I want to know why the error occurs and how to fix it.

MacOS 11.2.2
Apple M1 chip

I am always grateful for your information.
Thanks.

**Comment by Vincen-Jo** [comment]
Thanks for your fast response.
Let's find out where the file is.

**Comment by ianhbell** [comment]
What happens if you comment out (or delete) the line that tries to do the libquadmath.a copy? Should be lines 168-69 I think.

**Comment by Vincen-Jo** [comment]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/80340673/110502703-ca7bd280-813e-11eb-8fa3-2cc5aca89fba.png">

I think it has been resolved.
Thanks!^_^

**Comment by ianhbell** [comment]
Hmm.  Does the generated shared library work?

**Comment by Vincen-Jo** [comment]
Here is Korea.
It's too latem so check it out tomorrow.

**Comment by Vincen-Jo** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/80340673/110503474-9228c400-813f-11eb-95c7-98c7071f866c.png">
It seems that the error occurs in the next command as well.
It seems to be a problem that occurs because I don't have any knowledge in this field.
I will study a little more and try.

**Comment by ianhbell** [comment]
How are you ultimately going to call the shared library?  Python?

**Comment by Vincen-Jo** [comment]
I am trying to do this to link refprop to Excel on macOS.

**Comment by ianhbell** [comment]
Ah.  Excel+MacOS is a whole additional level of complexity.

**Comment by ianhbell** [comment]
Can you install Python 3.x via homebrew and then install numpy into that version?  Your numpy version is unhappy.

**Comment by Vincen-Jo** [comment]
Ok. let’s try again tomorrow. 

I have to sleep to go to work tomorrow. ^_^

Thanks again for the help.

**Comment by ianhbell** [comment]
Sounds good.  We'll get it working, somehow.

**Comment by Vincen-Jo** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/80340673/111040305-bb19c380-8475-11eb-905e-80b78ece9f4f.png">

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/80340673/111040346-f3210680-8475-11eb-9478-f6fb89019e72.png">

<img width="1907" alt="image" src="https://user-images.githubusercontent.com/80340673/111040398-25caff00-8476-11eb-91f9-ecf210c1a9de.png">

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/80340673/111040248-68400c00-8475-11eb-8e7f-d276c3c02556.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80340673/111040497-81958800-8476-11eb-85fb-11190c7a9f13.png">

I think the library file has been created normally, but when I try to run it in Excel, an error occurs and Excel quits. :(

**Comment by ianhbell** [comment]
Well, that's not good, but it seems you did everything properly.

**Comment by ianhbell** [comment]
Looks like maybe some sort of MacOS 11 incompatability.  As I said, I don't have access to MacOS 11 yet, so don't have means to debug.  Can you use Python? We could see if it is an Excel issue or what.

**Comment by Vincen-Jo** [comment]
Thank you for answer.
Let's try it in Python.
It will take time again because I need to get additional information to do it with Python. :)

**Comment by Vincen-Jo** [comment]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/80340673/111073714-09d16700-8523-11eb-9711-c24b5f0aa6f8.png">

I think ibrefprop.dylib was created incorrectly.
What do you think about this?

**Comment by ianhbell** [comment]
Did you build the shared library on the machine you ran it on?  It seems like not since the arch doesn't match.

**Comment by Vincen-Jo** [comment]
Are there any related tutorials?

**Comment by ianhbell** [comment]
I think you are doing things properly.  Did you build on the machine you are testing on?

**Comment by ianhbell** [comment]
There's info here: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python#ctypes-wrapper

**Comment by Vincen-Jo** [comment]
As you mentioned, I built on the machine under test.
Let's study more and find a solution.
Thank you. :)

**Comment by ianhbell** [comment]
Hmm.  I haven't seen this sort of thing before.  I wonder if it is actually a problem in the dependent libraries.  Can you show me the output of 
```
otool -L librefprop.dylib
```

**Comment by Vincen-Jo** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/80340673/111183528-54baaf80-85f3-11eb-859f-f227319484c4.png">

here is screenshot.

**Comment by ianhbell** [comment]
Good in one sense - no additional runtime dependencies (that's the point of static linking).  Bad that it doesn't work in this case.

**Comment by ianhbell** [comment]
Really to find a workaround I'm going to need to get access to an M1 mac and fiddle.

**Comment by Vincen-Jo** [comment]
ok.
I don't know when that is, but I'll wait. :)
Thanks for the help.

**Comment by ianhbell** [comment]
Sorry I don't have more useful feedback to share at this point.

**Comment by Vincen-Jo** [comment]
This problem seems to be happening on the M1 Mac.
Today, I confirmed that REFPROP and Excel work normally with my colleague Intel Mac.

Perhaps it is caused by GCC not being 100% compatible with the M1 chipset.

**Comment by ianhbell** [comment]
Yes, it seems to be some sort of incompatibility, though it is not clear what the origin is.  Debugging these sorts of things on MacOS can be surprisingly tricky.

**Comment by ianhbell** [comment]
By any chance do you have access to MacOS 11 on a non-M1 chip?

**Comment by Vincen-Jo** [comment]
I have already tried the test with an intel chipset mac(MacOS11 Big Sur).
In the above environment, Refprop work normally in Excel.

**Comment by ianhbell** [comment]
Thanks, that's a very useful datapoint.  So it appears the problem is really with M1 chipset compatibility.

**Comment by Vincen-Jo** [comment]
I agree with you.

Thank you for your continued interest.

**Comment by Rekingballer** [comment]
Hi Ian,

I'm also working with an M1 MacBook and can confirm that I have gone through the exact same issues, with the architecture of the built library ultimately being wrong. I've also tried the gcc build for m1 Big Sur found here: [http://hpc.sourceforge.net](http://hpc.sourceforge.net) to no avail. Is there no way to force a 64 bit build in the same way that I can be done for a 32 bit build?

No worries if there's no update on this,  I understand apple silicon is still relatively niche stuff at this point. Thanks!

**Comment by ianhbell** [comment]
I still don't have a M1 chip, so I sadly have no idea where to start with debugging help.

**Comment by trirex** [comment]
I've been trying to get REFPROP working in  Excel for M1.  The CMAKE process worked fine on my M1 MacBook Pro and produced a libreprop.dylib that works just fine in python, but it does not work with Excel.  I believe the issue is that Microsoft started compiling Excel for Apple Silicon rather than Intel which is why it does not work.  Python is still using an Intel compilation which is why it still works.    I believe a potential solution for Excel is to compile a version of  librefprop.dylib for apple silicon specifically.    I don't know how to make this compilation, but I'm still looking.

**Comment by ianhbell** [comment]
I'm not sure how Microsoft could compile Excel for Intel, but run on M1, but maybe that is true.  Without an M1, I have no idea where to start looking.

**Comment by trirex** [comment]
The macOS activity monitor tells whether an app is Apple or Intel.  Microsoft compiles Office apps as universal meaning the app contains both the Intel & M1 version in the same executable. I'm pretty sure this is why REFPROP is not working on M1 Macs.    You can see in my Activity Monitor (Kind column) screen shot that Excel is a native Apple app.  You can also see that OneDrive is an Intel app.

GFORTAN compiles for Intel.  I see a version is in development for M1, but its experimental at this point in time and I have not tried using it.   Intel has no plans to build native M1 compilers. 

I think once GNU has a native M1 compiler that the librefprop.dylib will likely start working on M1's.   

I also have a iMac with an Intel Processor and REFROP works in EXCEL using the latest macOS Monterey.   From my testing, it matches exactly the Windows version.


<img width="358" alt="Screen Shot 2021-11-15 at 9 16 09 AM" src="https://user-images.githubusercontent.com/20152073/141797019-dec6c2b6-ad38-4db6-b65c-3ab36caa0299.png">

**Comment by trirex** [comment]
I got REFPROP to work using EXCEL on a M1 Mac Pro.   You need to make sure you tell Mac to use Rosetta which provides backward compatibility.   See this https://www.howtogeek.com/702982/how-to-launch-the-intel-version-of-a-universal-mac-app-on-apple-silicon/ for more info on how to Force macOS to use the compatible version of EXCEL.

**Comment by ianhbell** [comment]
Care to update the docs with a pull request?

**Comment by trirex** [comment]
I can do that.  I am relatively new to GitHub.  How do I make a pull request to update the documentation?

**Comment by ianhbell** [comment]
Should be as simple as click the edit button, the pencil thing here: https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/Excel/README.md: 

![image](https://user-images.githubusercontent.com/11966765/146944901-2a391330-a34a-49e6-8e34-68c9e83de200.png)

**Comment by trirex** [comment]
Fine

**Comment by gautam-subburaj** [comment]
@ianhbell 

Hi Ian I tried the same thing as Vincen and recieved same error as him.
Please help so that I can use REFPROP in M1 Mac Air.


`vipinvenugopal@Vipins-Air ~ % cmake .. -DCMAKE_BUILD_TYPE=Release  
zsh: command not found: cmake
vipinvenugopal@Vipins-Air ~ % cd /Users/vipinvenugopal/REFPROP-cmake/build 
vipinvenugopal@Vipins-Air build % cmake .. -DCMAKE_BUILD_TYPE=Release         
zsh: command not found: cmake
vipinvenugopal@Vipins-Air build % export PATH=/usr/local/opt/brew/bin:$PATH   
vipinvenugopal@Vipins-Air build % cmake .. -DCMAKE_BUILD_TYPE=Release      
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 11.2.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/homebrew/bin/gfortran - skipped
DONE!
-- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 (found version "3.8.5") 
-- DEFSYM_FLAG: 
-- darwin
Missing from PASS_CMN_tokens:  ['ABFLASHdll', 'VIRBCD12dll', 'VIRTAUdll']
Missing from REFPROP_lib.h: []

-- Path to libquadmath.a:libquadmath.a
-- Copied libquadmath.a here.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vipinvenugopal/REFPROP-cmake/build
vipinvenugopal@Vipins-Air build % cmake --build .
Scanning dependencies of target refprop
[  6%] Building Fortran object CMakeFiles/refprop.dir/fortran/CORE_ANC.FOR.o
[ 12%] Building Fortran object CMakeFiles/refprop.dir/fortran/CORE_FEQ.FOR.o
[ 18%] Building Fortran object CMakeFiles/refprop.dir/fortran/CORE_PR.FOR.o
[ 25%] Building Fortran object CMakeFiles/refprop.dir/fortran/FLSH_SUB.FOR.o
[ 31%] Building Fortran object CMakeFiles/refprop.dir/fortran/MIX_HMX.FOR.o
[ 37%] Building Fortran object CMakeFiles/refprop.dir/fortran/PROP_SUB.FOR.o
[ 43%] Building Fortran object CMakeFiles/refprop.dir/fortran/REFPROP.FOR.o
/Users/vipinvenugopal/REFPROP-cmake/fortran/REFPROP.FOR:5589:72:

 5589 |          if (ABS(iErrPrnt).eq.3) pause           !If your compiler complains about this line, just delete it.
      |                                                                        
Warning: Deleted feature: PAUSE statement at (1)
[ 50%] Building Fortran object CMakeFiles/refprop.dir/fortran/SAT_SUB.FOR.o
[ 56%] Building Fortran object CMakeFiles/refprop.dir/fortran/SETUP.FOR.o
[ 62%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNSP.FOR.o
[ 68%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNS_TCX.FOR.o
[ 75%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNS_VIS.FOR.o
[ 81%] Building Fortran object CMakeFiles/refprop.dir/fortran/UTILITY.FOR.o
[ 87%] Building Fortran object CMakeFiles/refprop.dir/fortran/DLLFILES/PASS_FTN.FOR.o
[ 93%] Linking Fortran shared library librefprop.dylib
[ 93%] Built target refprop
[100%] About to build the REFPROP.h header file w/ /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8;-u;/Users/vipinvenugopal/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/vipinvenugopal/REFPROP-cmake/fortran/DLLFILES;--python-exe;/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /Users/vipinvenugopal/REFPROP-cmake/fortran/DLLFILES/PASS_FTN.FOR
numpy version: 1.22.3
Deleting REFPROP.pyf
[100%] Built target REFPROP_H
vipinvenugopal@Vipins-Air build % python3
Python 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> home = '/usr/local/REFPROP/'
>>> from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
>>> RP = REFPROPFunctionLibrary(home)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ctREFPROP/ctREFPROP.py", line 164, in REFPROPFunctionLibrary
    dll = loader_fcn(full_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/REFPROP/librefprop.dylib, 0x0006): tried: '/usr/local/REFPROP/librefprop.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
>>> 
`

**Comment by ianhbell** [comment]
The problem is that the generated shared library has arm64 architecture (native for M1), but somehow your python is looking for x86_64.  Are you running all this on the same machine? Otherwise you might want to make a universal build with both, though I'm not quite sure how one would manage that.  I don't have access to an M1 currently.

**Comment by trirex** [comment]
I have REFPROP working in both EXCEL & Python on my M1  Mac.   I updated the readme with instructions but the readme was never published.  


I got REFPROP to work using EXCEL on a M1 Mac Pro. You need to make sure you tell Mac to use Rosetta which provides backward compatibility. See this https://www.howtogeek.com/702982/how-to-launch-the-intel-version-of-a-universal-mac-app-on-apple-silicon/ for more info on how to Force macOS to use the compatible version of EXCEL.

**Comment by gautam-subburaj** [comment]
I have installed python using brew and then did the further commands.
Do i need to run the cmake build command as this?

`cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3`

Does this mean that the build command is running with python GUI version installed locally from python.org in local folder seperately?

**Comment by gautam-subburaj** [comment]
@trirex 
I don't know where the updated procedure for the REFPROP installation is. 
Can u please send it to me so that I can resolve this issue

**Comment by trirex** [comment]
https://github.com/trirex/REFPROP-wrappers/blob/patch-1/wrappers/Excel/README.md

**Comment by ianhbell** [comment]
@trirex Can you please make pull request with edit?

**Comment by ianhbell** [comment]
Somehow you have to convince python to use rosetta to load the x86_64 version. I don't know how to to do that.
